### ISSUE TITLE
Error API call

### ISSUE THREAD

**Issue by jnthnmillet** [PayMaya/PayMaya-PHP-SDK#23]
Trying to run your sample code and encountered an error.

`<br />
<b>Fatal error</b>: Uncaught Exception: Error API call in
/storage/ssd4/275/12315275/public_html/paymaya/vendor/paymaya/paymaya-sdk/lib/PayMaya/Core/HTTPConnection.php:50
Stack trace:
#0
/storage/ssd4/275/12315275/public_html/paymaya/vendor/paymaya/paymaya-sdk/lib/PayMaya/Core/CheckoutAPIManager.php(57):
PayMaya\Core\HTTPConnection-&gt;execute('{&quot;url&quot;:null,&quot;bu...')
#1 /storage/ssd4/275/12315275/public_html/paymaya/vendor/paymaya/paymaya-sdk/lib/PayMaya/API/Checkout.php(34):
PayMaya\Core\CheckoutAPIManager-&gt;initiateCheckout(Array)
#2 /storage/ssd4/275/12315275/public_html/paymaya/vendor/paymaya/paymaya-sdk/sample/Checkout/ItemCheckout.php(44):
PayMaya\API\Checkout-&gt;execute()
#3 {main}
thrown in
<b>/storage/ssd4/275/12315275/public_html/paymaya/vendor/paymaya/paymaya-sdk/lib/PayMaya/Core/HTTPConnection.php</b> on
line <b>50</b><br />`

**Comment by glenjoyr** [comment]
i have the same error,

**Comment by glenjoyr** [comment]
bro try to install this:
https://curl.se/docs/caextract.html
![image](https://user-images.githubusercontent.com/104476739/177583958-50e43691-d22e-4cee-a558-2ede2eb1a5d0.png)
